name: Checkout
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        checkout: [actions/checkout@v2, actions/checkout@v3, actions/checkout@v4]
    steps:
      - name: checkout
        uses: ${{ needs.checkout.outputs.checkout }}
