name: Checkout
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: |
          npm install
          npm test
        
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker image build -t eppjonathan/greeting-app .

      - name: Push image
        run: docker push eppjonathan/greeting-app:latest

  bring-alive:
    runs-on: [aws-ec2]
    needs: publish
    steps:
      - name: fetch image
        run: docker pull eppjonathan/greeting-app:latest

      - name: remove existing container
        run: docker rm -f greeting-app || true

      - name: run container
        run: docker run -d -p 3000:3000 --name greeting-app eppjonathan/greeting-app:latest

